# Change these first
owner: AsmSafone # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: SafoneAPI
    url: https://api.safone.dev
  - name: Github API
    url: https://gh-api.glitch.me
  - name: 24/7 Radio
    url: https://rtmp.fly.dev/start
  - name: My Meet
    url: https://my-meet.onrender.com
  - name: Auth Bot
    url: https://auth-w1dd.onrender.com
  - name: Forward Bot
    url: https://aforward.onrender.com
  - name: Udemy Bot
    url: https://udemy-rmpn.onrender.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.safone.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
